package com.andreev.rental.logic.util;

public enum ERegexValidator {
	ID,
	BRAND_NAME,
	CAR_DESCRIPTION,
	CAR_DESCRIPTION_CONSUMPTION,
	CAR_DESCRIPTION_DESCRIPTION,
	CAR_DESCRIPTION_DOORS,
	CAR_DESCRIPTION_SEATS,
	CAR_DESCRIPTION_PRICE,
	CAR_DESCRIPTION_IMG,
	CAR_MODEL_NAME,
	ORDER_FROM,
	ORDER_INFO,
	ORDER_STATUS,
	ORDER_TO,
	ORDER_TOTAL,
	ORDER_DETAIL_DESCRIPTION,
	ORDER_DETAIL_PRICE,
	USER_ADDRESS,
	USER_EMAIL,
	USER_NAME,
	USER_PASSPORT,
	USER_PASSWORD,
	USER_PHONE,
	USER_SURNAME;
}